<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageId>Titanic.Entity</PackageId>
    <Version>1.1.0</Version>
    <Authors>demon3t</Authors>
    <Description>Entity ORM and HTTP API layer for Titanic.</Description>
    <RepositoryUrl>https://github.com/demon3t/Titanic</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>orm;entity;http-api;database;postgresql</PackageTags>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludeCommonOutputInPackage</TargetsForTfmSpecificBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Attributes\ColumnAttribute.cs~RF50b783.TMP" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Titanic.Common\Titanic.Common.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\Titanic.Db\Titanic.Db.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
  </ItemGroup>

  <Target Name="IncludeCommonOutputInPackage" DependsOnTargets="ResolveReferences">
    <ItemGroup>
      <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths->WithMetadataValue('ReferenceSourceTarget', 'ProjectReference')->WithMetadataValue('Filename', 'Titanic.Common'))" />
    </ItemGroup>
  </Target>

</Project>
